### ISSUE TITLE
Does not work with node 0.10

### ISSUE THREAD

**Issue by rvdwijngaard** [elbuo8/sqs.js#7]
Hi, 

Your library does not work properly with node version 0.10; 

/home/ubuntu/workspace/em_machinepartservice/node_modules/sqs.js/lib/reader.js:34  
Reader.prototype = Object.create(Emitter.prototype);  
                          ^  
TypeError: Object prototype may only be an Object or null  
    at Function.create (native)  
    at Object.<anonymous> (/home/ubuntu/workspace/em_machinepartservice/node_modules/sqs.js/lib/reader.js:34:27)  
    at Module._compile (module.js:456:26)  
    at Object.Module._extensions..js (module.js:474:10)  
    at Module.load (module.js:356:32)  
    at Function.Module._load (module.js:312:12)  
    at Module.require (module.js:364:17)  
    at require (module.js:380:17)  
    at Object.<anonymous> (/home/ubuntu/workspace/em_machinepartservice/node_modules/sqs.js/index.js:3:14)  
    at Module._compile (module.js:456:26)                        

This statement is causing the problem: 
Reader.prototype = Object.create(Emitter.prototype);

Reason is that the Emitter.prototype is _undefined_ in 0.10.

**Comment by elbuo8** [comment]
This was intentional.

**Comment by rvdwijngaard** [comment]
Can you please explain why?

**Comment by elbuo8** [comment]
Couldn't find a reason not to. Updated it to support `0.10.x`.

**Comment by rvdwijngaard** [comment]
Great thanks.

-----Oorspronkelijk bericht-----
Van: "Yamil Asusta" notifications@github.com
Verzonden: ‎21-‎3-‎2015 19:16
Aan: "elbuo8/sqs.js" sqs.js@noreply.github.com
CC: "rvdwijngaard" rhvdwijngaard@gmail.com
Onderwerp: Re: [sqs.js] Does not work with node 0.10 (#7)

Couldn't find a reason not to. Updated it to support 0.10.x.
